# Generated by Django 4.1.6 on 2023-02-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_title',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
