# Generated by Django 4.1.6 on 2023-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='course_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
