# Generated by Django 4.1.6 on 2023-02-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productfile_course_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
