# Generated by Django 4.1.7 on 2023-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='audience',
            field=models.CharField(blank=True, choices=[('в настоящий момент нет', 'в настоящий момент нет'), ('у меня маленькая аудитория', 'у меня маленькая аудитория'), ('у меня достаточная аудитория', 'у меня достаточная аудитория')], max_length=85),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, choices=[('лично, частным образом', 'лично, частным образом'), ('лично, профессионально', 'лично, профессионально'), ('онлайн', 'онлайн'), ('другое', 'другое')], max_length=85),
        ),
    ]
