# Generated by Django 4.1.6 on 2023-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experience',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=85),
        ),
    ]
