# Generated by Django 4.1.6 on 2023-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_activation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='audience',
            field=models.CharField(blank=True, max_length=85),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, max_length=85),
        ),
    ]
