# Generated by Django 4.1.6 on 2023-02-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_audience_customuser_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
