# Generated by Django 4.1.7 on 2023-02-23 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(blank=True, max_length=85)),
                ('language', models.CharField(blank=True, max_length=55)),
                ('site_url', models.CharField(blank=True, max_length=85)),
                ('twitter_url', models.CharField(blank=True, max_length=85)),
                ('facebook_url', models.CharField(blank=True, max_length=85)),
                ('linkedin_url', models.CharField(blank=True, max_length=85)),
                ('youtube_url', models.CharField(blank=True, max_length=85)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_hidden_courses', models.BooleanField(default=False)),
                ('promotions', models.BooleanField(default=False)),
                ('mentor_ads', models.BooleanField(default=False)),
                ('email_ads', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
