# Generated by Django 4.1.6 on 2023-02-12 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(blank=True, max_length=85)),
                ('language', models.CharField(blank=True, max_length=55)),
                ('site_url', models.CharField(blank=True, max_length=85)),
                ('twitter_url', models.CharField(blank=True, max_length=85)),
                ('facebook_url', models.CharField(blank=True, max_length=85)),
                ('linkedin_url', models.CharField(blank=True, max_length=85)),
                ('youtube_url', models.CharField(blank=True, max_length=85)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
