# Generated by Django 4.1.7 on 2023-02-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_likecomment_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomment',
            name='dislike',
        ),
    ]
