# Generated by Django 4.1.7 on 2023-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_likecomment_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomment',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
    ]
