# Generated by Django 4.1.7 on 2023-02-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeconderyCategory',
            fields=[
                ('secondery_category', models.SlugField(default='Python', primary_key=True, serialize=False)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondery_categorys', to='course.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='secondery_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_secondery_category', to='course.seconderycategory'),
            preserve_default=False,
        ),
    ]
