# Generated by Django 4.1.7 on 2023-02-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_seconderycategory_course_secondery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='seconderycategory',
            name='test',
            field=models.CharField(default='testing', max_length=55),
        ),
    ]
