# Generated by Django 4.1.7 on 2023-02-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_category_alter_course_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.SlugField(default='Education', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Начальный', 'Начальный'), ('Средний', 'Средний'), ('Профессиональный', 'Профессиональный'), ('Все уровни', 'Все уровни')], max_length=25),
        ),
    ]
