# Generated by Django 4.1.7 on 2023-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_seconderycategory_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seconderycategory',
            name='test',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='Development', max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seconderycategory',
            name='secondery_category',
            field=models.CharField(default='Python', max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(default='Web Development', max_length=60, primary_key=True, serialize=False),
        ),
    ]
