# Generated by Django 4.1.7 on 2023-02-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_coursefile_course_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Video-content/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='course_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_files', to='course.coursefile'),
        ),
    ]
