# Generated by Django 4.1.7 on 2023-02-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_video_alter_file_course_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseitem',
            old_name='course',
            new_name='course_id',
        ),
        migrations.AddField(
            model_name='coursefile',
            name='file',
            field=models.FileField(default=1, upload_to='Course-content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='course_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_files', to='course.courseitem'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
