# Generated by Django 4.1.7 on 2023-02-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_course_courseitem_course_id_coursefile_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefile',
            old_name='course_item_id',
            new_name='course_file',
        ),
    ]
